server:
  port: 1360
spring:
  application:
    name: config
#  profiles:
#    active: dev
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.7:8099/huwenzhe/springcloud-config.git
#          default-label: master   #解决监控down
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1360