server:
  port: 1350

spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.7:8099/huwenzhe/springcloud-config.git
          default-label: master   #解决监控down
---
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1340/eureka/  #注册中心地址
    registry-fetch-interval-seconds: 10
#---
#spring:
#  profiles: prd
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5682
#    username: pig
#    password: lengleng
#  cloud:
#    config:
#      retry:
#        initial-interval: 3000
#        multiplier: 1.5
#        max-interval: 20000
#        max-attempts: 6
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://pig:gip6666@eureka:1025/eureka

# 关闭安全管理
#management:
#  security:
#    enabled: false
#endpoints:
#  health:
#    sensitive: false