server:
  port: 1601
spring:
  jpa:
    properties:
      hibernate:
        mysql-dialect:
          org.hibernate.dialect.MySQL5InnoDBDialect
#        pgsql-dialect:
#          org.hibernate.dialect.PostgreSQL94Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSl=false&serverTimezone=GMT%2B8
      username: root
      password: shinian
      driver-class-name: com.mysql.cj.jdbc.Driver
#    pgsql:
#      url: jdbc:postgresql://192.168.1.15:5432/mrl?useSSL=false
#      username: postgres
#      password: postgres
#      driver-class-name: org.postgresql.Driver
  application:
    name: circle-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1601
#解决com.netflix.client.ClientException: Load balancer does not have available server for client：xxx
#2.0版本默认不开启了
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
