server:
  port: 1601
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    mrl:
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSl=false&serverTimezone=GMT%2B8
      username: root
      password: shinian
      driver-class-name: com.mysql.jdbc.Driver
    test:
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSl=false&serverTimezone=GMT%2B8
        username: root
        password: shinian
        driver-class-name: com.mysql.jdbc.Driver
  application:
    name: circle-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1601
#解决com.netflix.client.ClientException: Load balancer does not have available server for client：xxx
#2.0版本默认不开启了
feign:
  hystrix:
    enabled: true
