server:
  port: 1343
  context-path: /sso
# REDIS (RedisProperties)
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

  jpa:
    generate-ddl: false
    show-sql: true

  datasource:
    url: jdbc:mysql://192.168.1.10:3306/xy_yjgl_sh?useUnicode=true&characterEncoding=UTF-8&useSSl=false
    username: root
    password: xinyuan
    driver-class-name: com.mysql.jdbc.Driver

  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/

  application:
    name: sso

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1343/sso

security:
  user:
    name: xinyuan
    password: xinyuan1525