eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
spring:
  application:
    name: gateway
server:
  port: 1600
#  context-path: /gateway
zuul:
  routes:
    test-server: /test/**
    order-service: /order/**
  host:
    max-per-route-connections: 20
    max-total-connections: 200
    socket-timeout-millis: 3000
  ribbon-isolation-strategy: semaphore
hystrix:
  metrics:
    polling-interval-ms: 3000
