eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1340/eureka/  #注册中心地址
spring:
  application:
    name: gateway
server:
  port: 1600
#  context-path: /gateway
zuul:
    relation-service:
      path: /relation/**
      service-id: relation-service
    circle-service:
      path: /circle/**
      service-id: circle-service
  sensitive-headers:

#      sensitiveHeaders:
#      serviceId:  order-service
#  add-proxy-headers: true
#  add-host-header: true
