eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
spring:
  application:
    name: gateway
server:
  port: 1600
#  context-path: /gateway
zuul:
  routes:
    test-server:
      path: /test/**
      service-id: test-server
    order-service:
      path: /order/**
      service-id: order-service
  sensitive-headers:
#      sensitiveHeaders:
#      serviceId:  order-service
  add-proxy-headers: true
  add-host-header: true

#auth-server: http://localhost:1343/sso # sso-server地址
#security:
#  oauth2:
#    client:
#      client-id: xinyuan
#      client-secret: xinyuan1525
#      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
#      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
#    resource:
#      jwt:
#        key-uri: ${auth-server}/oauth/token_key #解析jwt令牌所需要密钥的地址
