##spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.prefix=/WE
##spring.mvc.view.suffix=.jsp
#spring.mvc.view.suffix=.jsp

# 页面默认前缀目录
server:
  port: 9042
spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
## 响应页面默认后缀
      suffix: .jsp
## 自定义属性，可以在Controller中读取
#application.hello=Hello GOD
#关闭默认模板引擎
#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10