#---------------------------------------------
server:
  port: 1330
#---------------------------------------------
spring:
  application:
    name: gateway
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
zuul:
  routes:
    #圈子服务
    circle:
      path: /circle/**
      serviceId: circle-service
    #关系服务
    relation:
      path: /relation/**
      serviceId: relation-service
  host:
    max-total-connections: 200
    max-per-route-connections: 20
#---------------------------------------------
swagger:
  butler:
    auto-generate-from-zuul-routes: true
    generate-routes: circle, relation
    resources:
      circle:
        api-docs-path: v2/api-docs
      relation:
        api-docs-path: v2/api-docs
#---------------------------------------------