#---------------------------------------------
server:
  port: 1330
#---------------------------------------------
spring:
  application:
    name: gateway
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1300/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
zuul:
  routes:
    #圈子服务
    circle:
      path: /circle/**
      serviceId: circle-service
    #关系服务
    relation:
      path: /relation/**
      serviceId: relation-service
    #认证服务
    oauth:
      path: /oauth/**
      serviceId: oauth-service
    #消息服务
    im:
      path: /im/**
      serviceId: im-service
      #消息服务
    user:
      path: /user/**
      serviceId: user-service
  host:
    max-total-connections: 200
    max-per-route-connections: 20
    connect-timeout-millis: 5000
  sensitive-headers: null
#---------------------------------------------
#---------------------------------------------
swagger:
  butler:
    auto-generate-from-zuul-routes: true
    generate-routes: circle, relation, user
    resources:
      circle:
        api-docs-path: v2/api-docs
      relation:
        api-docs-path: v2/api-docs
      user:
        api-docs-path: v2/api-docs
#---------------------------------------------
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:1360/user

