server:
  port: 1901
spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1901
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
elasticsearch:
  ip: 111.230.28.218
  cluster:
    name: cloud
  port: 9300
  pool: 5
