server:
  port: 1701
spring:
  application:
    name: monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1701

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
