#---------------------------------------------
server:
  port: 1320
#---------------------------------------------
spring:
  application:
    name: monitor
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
  instance:
    hostname: localhost
    instance-id: http://${eureka.instance.hostname}:${server.port}
#---------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
