#---------------------------------------------
server:
  port: 1300
#---------------------------------------------
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 10
  server:
    enable-self-preservation: false #关闭安全模式,生产环境不建议
#---------------------------------------------