#---------------------------------------------
server:
  port: 1901
#---------------------------------------------
spring:
  application:
    name: stream
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myInput:
          destination: minestream #指定输入通道对应的主题名
          group: stream #指定该应用实例属于 stream 消费组
          consumer:
            partitioned: true #通过该参数开启消费者分区功能
        myOutput:
          destination: minestream
          producer:
            partitionKeyExpression: payload #通过该参数指定了分区键的表达式规则，可以根据实际的输出消息规则配置 SpEL 来生成合适的分区键
            partitionCount: 2
      instance-count: 2  #该参数指定了当前消费者的总实例数量
      instance-index: 0  #该参数设置了当前实例的索引号，从 0 开始，最大值为 spring.cloud.stream.instance-count 参数 - 1
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/  #注册中心地址
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------