#---------------------------------------------
server:
  port: 1320
#---------------------------------------------
spring:
  application:
    name: monitor
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
