#---------------------------------------------
server:
  port: 1310
#---------------------------------------------
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.7:8099/huwenzhe/springcloud-config.git
          default-label: master #解决监控down
#---------------------------------------------
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
#---------------------------------------------
# http://blog.sina.com.cn/s/blog_6d3c1ec60102xk3x.html
    # 关闭安全管理
#management:
#  security:
#    enabled: false
#endpoints:
#  health:
#    sensitive: false
#---------------------------------------------
#  rabbitmq:
#        host: localhost
#        port: 5672
#        username: mrl
#        password: shinian
#---------------------------------------------