server:
  port: 1902
spring:
  application:
    name: stream
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myInput:
          #指定输入通道对应的主题名
          destination: minestream
        myOutput:
          destination: minestream


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1340/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:1901
