auth-server: http://localhost:1343/sso # sso-server地址
server:
  port: 1400
  context-path: /feign
spring:
  application:
    name: feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
feign:
  hystrix:
    enabled: true #开启器默认断路器

security:
  oauth2:
    client:
      client-id: xinyuan
      client-secret: xinyuan1525
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    resource:
      id: order-service
      user-info-uri: ${auth-server}/user
      prefer-token-info: true