server:
  port: 1343
  context-path: /feign
spring:
  application:
    name: feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1340/eureka/  #注册中心地址
feign:
  hystrix:
    enabled: true #开启器默认断路器