#---------------------------------------------
server:
  port: 1420
#---------------------------------------------
spring:
  application:
    name: search-service
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/  #注册中心地址
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#---------------------------------------------
elasticsearch:
  ip: 192.168.1.10
  cluster:
    name: yjgl
  port: 9300
  pool: 5
