#---------------------------------------------
server:
  port: 1343
  servlet:
    context-path: /sso
#---------------------------------------------
spring:
  application:
    name: sso-server
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSl=false
    username: root
    password: xinyuan
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: xinyuan
      password: xinyuan1525
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1300/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------